src/CompanyINC.UI.Site/Areas/Produtos/Controllers/CadastroController.cs
using Microsoft.AspNetCore.Mvc;

namespace CompanyINC.UI.Site.Areas.Produtos.Controllers
{
    [Area("Produtos")]
    public class CadastroController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/CompanyINC.UI.Site/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace CompanyINC.UI.Site.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/CompanyINC.UI.Site/Areas/Produtos/Views/Cadastro/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Cadastro de Produto</h1>

src/CompanyINC.UI.Site/Views/Home/Index.cshtml
<h1>Olá Mundo</h1>

src/CompanyINC.UI.Site/Views/Shared/_Layout.cshtml
<html>
    <head>
        <title>@ViewData["Title"] - Minha App Modelo</title>

        <environment include="Development">
            <link href="~/css/site_bundle.min.css" rel="stylesheet" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/css/bootstrap.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
                  crossorigin="anonymous"
                  integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
            <link href="~/css/site.css" rel="stylesheet" />
        </environment>
        
        <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.css" />
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppModelo</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Produtos" asp-controller="Cadastro" asp-action="Index">Cadastro</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                Minha App Modelo - <email email-domain="gmail.com">contato</email> - <email>suporte</email>
            </div>
        </footer>

        <environment include="Development">
            <script src="~/js/site_bundle.min.js"></script>
            <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                    asp-fallback-src="~/lib/jquery/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
            </script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                    asp-fallback-src="~/lib/bootstrap/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
            </script>
            <script src="~/css/site.css"></script>
        </environment>
    </body>
</html>